#Global Properties
browserName = chrome
websiteURL = https://en.wikipedia.org/wiki/Main_Page

#Home Page Locators
logInButton_xpath = //*[@id='pt-login-2']/a/span

#Login Page Locators
usernameTextBox_xpath = //*[@id='wpName1']
passwordTextBox_xpath = //*[@id='wpPassword1']